use proyecto_db;

INSERT INTO usuario(Carnet, Nombres, Apellidos, Contrasena, Correo) 
VALUES
(201612174, 'Alberto', 'Reyes', '1234', 'random0@gmail.com'),
(201900957, 'Karina', 'Ramirez', '1234', 'random1@gmail.com'),
(201403784, 'Erick', 'Lopez', '1234', 'random2@gmail.com'),
(201906180, 'Julio', 'Wu', '1234', 'random3@gmail.com'),
(201701108, 'Hugo', 'Arreaga', '1234', 'random4@gmail.com'),
(201908384, 'Kervin', 'Cardona', '1234', 'random5@gmail.com');

INSERT INTO curso (CodigoCurso, Nombre) VALUES
(283,'Analisis y Diseno de Sistemas 1'), 
(785,'Analisis y Diseno de Sistemas 2'), 
(778,'Arq. de Computadoras y Ensambladores 1'), 
(779,'Arq. de Computadoras y Ensambladores 2'), 
(774,'Bases de Datos 1'), 
(775,'Bases de Datos 2'), 
(014,'Economia'), 
(790,'Emprendedores de Neg. Informaticos'), 
(772,'Estructura de Datos'), 
(787,'Gerenciales 2'), 
(972,'Inteligencia Artificial 1'), 
(770,'Intro a la Programacion y Computacion 1'), 
(771,'Intro a la Programacion y Computacion 2'), 
(796,'Lenguajes Formales y de Programacion'), 
(795,'Logica de Sistemas'), 
(773,'Manejo e Implementacion de Archivos'), 
(729,'Modelacion y Simulacion 1'), 
(720,'Modelacion y Simulacion 2'), 
(964,'Organizacion Computacional'), 
(781,'Org de Lenguajes y Compiladores 2'), 
(777,'Org Lenguajes y Compiladores 1'), 
(2025,'Practicas Iniciales'), 
(2036,'Practicas Intermedias'), 
(1,'Programacion Comercial 1'), 
(2,'Programacion de Computadoras 1'), 
(3,'Programacion de Computadoras 2'), 
(970,'Redes de computadoras 1'), 
(975,'Redes de Computadoras 2'), 
(797,'Seminario de Sistemas 1'), 
(798,'Seminario de Sistemas 2'), 
(281,'Sistemas Operativos 1'), 
(285,'Sistemas Operativos 2'), 
(786,'Sistemas Organizaciones y Gerenciales 1'), 
(780,'Software Avanzado'), 
(722,'Teoria de Sistemas 1'), 
(724,'Teoria de Sistemas 2'); 

INSERT INTO catedratico (NoCatedratico, Apellidos, Nombres) 
VALUES
(1,'MORALES PRADO', 'JOSE RICARDO'), 
(2,'GUEVARA ORELLANA', 'WILLIAM SAMUEL'), 
(3,'ALDANA LARRAZABAL', 'MIRNA IVONNE'), 
(4,'ESCOBAR LEIVA', 'OTTO RENE'), 
(5,'DIAS LOPEZ', 'GABRIEL ALEJANDRO'), 
(6,'RODRIGUEZ ACOSTA', 'OTTO AMILCAR'), 
(7,'ESPINO BARRIOS', 'LUIS FERNANDO'), 
(8,'LONGO MORALES', 'ALVARO GIOVANNI'), 
(9,'ARIAS', 'LUIS ALBERTO'), 
(10,'RALDA RECINOS DE ILLESCAS', 'ILEANA GUISELA'), 
(11,'MORALES RUIZ' , 'EVELYN CAROLINA'), 
(12,'ALTAN SAC' , 'LUDWING FEDERICO'), 
(13,'GUZMAN', 'JESUS ALBERTO'), 
(14,'HERNANDEZ GARCIA', 'ALVARO OBRAYAN'), 
(16,'VETTORAZZI ESPANA', 'LUIS ALBERTO'), 
(17,'ORELLANA LOPEZ' , 'MARLON FRANCISCO'), 
(18,'ZEPEDA AREVALO', 'BYRON RODOLFO'), 
(19,'VELASQUEZ OLIVA', 'MOISES EDUARDO'), 
(20,'VELIZ LINARES', 'HERMAN IGOR'), 
(21,'CALDERON MENDEZ', 'NEFTALI DE JESUS'), 
(22,'PEREZ TURK', 'MARLON ANTONIO'), 
(23,'ROJAS MORALES', 'CLAUDIA LICETH'), 
(24,'RUIZ JUAREZ' , 'JOSE MANUEL'), 
(25,'ESCOBAR ARGUETA', 'WILLIAM ESTUARDO'), 
(26,'ZAPETA GOMEZ', 'EDWIN ESTUARDO'), 
(27,'MORALES LOPEZ', 'LUIS MANUEL'), 
(28,'TALA AYERDI' , 'VIRGINIA VICTORIA'), 
(29,'AVILA PESQUERA DE MEDINILLA', 'FLORIZA FELIPA'), 
(30,'DIAZ ARDAVIN' , 'JUAN ALVARO'), 
(31,'PAZ CAMPOS', 'OSCAR ALEJANDRO'), 
(32,'CANCINOS RENDON', 'MIGUEL ANGEL'), 
(33,'FERNANDEZ CACERES', 'CESAR AUGUSTO'), 
(34,'LOPEZ LOPEZ', 'BAYRON WOSVELY'), 
(35,'SABAN RAXON', 'EDGAR RUBEN'), 
(36,'NAVARRO DELGADO', 'ERICK CARLOS ROBERTO'), 
(37,'BAUTISTA FUENTES', 'MARIO JOSE'), 
(38,'CASTILLO REYNA' , 'MANUEL HAROLDO'), 
(39,'LAJPOP AJPACAJA', 'KEVIN ADIEL'), 
(40,'MENENDEZ PEREZ', 'GUIPPSY JEANNIRA'), 
(41,'SILVA DE LOS ANGELES', 'JOSE ANIBAL'), 
(42,'HERNANDEZ RAMIREZ', 'PEDRO PABLO'), 
(43,'LOPEZ FERNANDEZ', 'MANUEL FERNANDO'), 
(44,'MENDEZ AGUILAR', 'SERGIO ARNALDO'), 
(45,'BATZ SAQUIMUX', 'CESAR ROLANDO'), 
(46,'MEDINILLA RODRIGUEZ', 'EVEREST DARWIN'), 
(47,'ALVAREZ MEJIA', 'JORGE LUIS'),
(48,'DE LEON SECAY', 'KEVIN ALBERTO'), 
(49,'URIAS COC', 'DANILO'), 
(50,'VELIZ SANDOVAL', 'JOSE MANUEL'),
(51,'GIRON REYES', 'DARWIN DODANY'),
(15,'LEAL CARDONA', 'SERGIO GEOVANY'),
(52, 'SANCHEZ TUCHEZ', 'SEBASTIAN');